### ISSUE TITLE
Looking to help.

### ISSUE THREAD

**Issue by fxb6476** [xerpi/vita-linux-loader#1]
Hello, what is the best way to start testing/helping to make this dream a reality. I have a hacked Vita running the latest Vita hack ("Trinity"). Component skills I'm c and c++. Seems as if the "loader" acts as a boot loader of sorts moving the image to RAM.
I think the bulk of the work lives in getting the kernel to actually use the Vita hardware.

Let me know how to get started testing :)

**Comment by xerpi** [comment]
Hi, take a look at this: https://gist.github.com/xerpi/5c60ce951caf263fcafffb48562fe50f

**Comment by fxb6476** [comment]
Quick question, when I load the Linux image onto the ps Vita, is this loaded in some sort of sandbox? My main concern here is, how do I get back out of Linux user land and back into the normal ps Vita OS lol

**Comment by xerpi** [comment]
Linux doesn't run in any sandbox but it runs in bare-metal `ARMv7 non-secure System mode`, this means that the PSVita OS is non-existent at this point (there's only the ARMv7 *secure* System mode but it's really small). To get back to the Vita OS you have to restart.

**Comment by fxb6476** [comment]
Ohhhh ok so we are in fact loading the image onto pure memory and handing over execution control to Linux, just like a boot loader does! Cool very, and dangerous lol is it possible to read the vitas boot loader at this point? Or is the bootloader on a separate memory chip?

**Comment by xerpi** [comment]
It is a bit dangerous, indeed. Check this if you want a bare-metal program that does more stuff such initializing the display or reading the buttons: https://github.com/xerpi/vita-baremetal-sample

Regarding the bootloader, check https://wiki.henkaku.xyz/vita/Security and https://wiki.henkaku.xyz/vita/Boot_Sequence
