### ISSUE TITLE
Boot(loader)-level initialization

### ISSUE THREAD

**Issue by IngwiePhoenix** [xerpi/vita-linux-loader#3]
I am currently getting more and more into how kernels, EFI and the likes work as I am taking a look at how much would have to be done to port alternative distributions like LineageOS etc. to the Razer Phone 2. In this process, I have seen that there are various ways bootloaders are implemented, which also reminded me, that during the h-encore setup on my PSVita, it mentioned writing to MBR - which I assume is one way the Vita decides where to boot like any traditional BIOS (or CSM these days).

So I would like to know if it is theoretically possible to boot Linux once the unit is turned on and skip over the Vita's OS entirely? For now, we still have a PSN Store and there is no real reason why someone would want to mainly boot into Linux - but later, a slimmed down software like Kodi might become useful as to extend the longevity of the device after the store has shut down.

**Comment by xerpi** [comment]
I think you want to take a look at: https://github.com/xerpi/vita-baremetal-loader
And this Linux loader: https://github.com/xerpi/vita-baremetal-linux-loader

Regarding booting directly to Linux, I think it's possible to dual-boot. For that ask @SKGleba

**Comment by IngwiePhoenix** [comment]
Thank you very much! :) There are a lot of concepts I want to explore and poke as I learn more about the Linux kernel - and adjanced topics - in general. Still very early to this, but it is still quite a lot of fun.

...And, better than just staring at a wall and growing a bigger cabin fever :)
